name: Deplot CodigoFacilito

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: ruta inicial
        run: pwd

      - name: checkout
        uses: actions/checkout@v4

      - name: ruta final
        run: ls -al

  job_outputs:
    needs: second_job
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.name-1.outputs.nombre }}

    steps:
      - name: Obtener nombre
        id: name-1
        run: echo "nombre=pacho" >> $GITHUB_OUTPUT

      - name: Leer nombre
        id: name-2
        run: echo "el nombre es ${{ steps.name-1.outputs.nombre }}"

  generar_artefacto:
    needs: job_outputs
    runs-on: ubuntu-latest

    steps:
      - name: Generar archivo
        run: |
          echo "Hola mundo en artifacto" >> test.log

      - name: subur artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  descargar_artefacto:
    needs: generar_artefacto
    runs-on: ubuntu-latest

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test