name: Deplot CodigoFacilito

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo
        run: echo "Hola mundo"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps:
      - name: segundo step
        run: echo "Segundo step"