name: Test jobs

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  first-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: First job
        run: echo Hello, world!


  second-job:
    # The type of runner that the job will run on
    needs: first-job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Second job
        run: echo Hello, world from second job!

  third-job:
    # The type of runner that the job will run on
    needs: first-job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Second job
        run: echo Hello, world from third job!
